name: Develop CI

on:
  pull_request:
    branches:
      - develop

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16, 18, 21.1]
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm ci

      - name: Fun Message Before Tests
        run: echo "🚀 Let's see how the tests go on Node.js ${{ matrix.node-version }}!"

      - name: Run Tests
        run: npm test

      - name: Fun Message After Tests
        run: echo "🎉 Great! Tests completed on Node.js ${{ matrix.node-version }}!"
